# Generated by Django 4.1.7 on 2024-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
